import { createHash } from 'node:crypto';
import type { IncidentRecord } from './wavemill-incident-model.ts';
import type { IncidentLinearConfig } from './config.ts';

const MAX_TITLE_LENGTH = 250;
const MAX_EVIDENCE_ITEMS = 12;

export class IncidentToLinearFormatter {
  formatIssueTitle(incident: IncidentRecord): string {
    const fingerprint = incident.fingerprint.slice(0, 12);
    return sanitizeLine(`[incident-${fingerprint}] ${incident.rootCauseClass}: ${incident.summary}`)
      .slice(0, MAX_TITLE_LENGTH);
  }

  formatIssueDescription(incident: IncidentRecord, config: IncidentLinearConfig): string {
    const related = relatedIssueIds(incident, config);
    return [
      `## Root Cause Class`,
      redactSensitiveContent(incident.rootCauseClass),
      '',
      `## Severity & Confidence`,
      `Severity: ${incident.severity}`,
      `Confidence: ${incident.confidence}`,
      `Category: ${incident.category}`,
      `Fingerprint: ${incident.fingerprint}`,
      '',
      `## Impact`,
      `Task: ${incident.taskId ?? '(repo)'}`,
      `Session: ${incident.session ?? '(unknown)'}`,
      `Occurrences: ${incident.occurrenceCount}`,
      `Window: ${incident.createdAt || '(unknown)'} to ${incident.lastObservedAt || '(unknown)'}`,
      '',
      `## Summary`,
      redactSensitiveContent(incident.summary),
      '',
      `## Operator Recommendation`,
      redactSensitiveContent(incident.operatorAction),
      '',
      `## Evidence Summary`,
      ...formatEvidenceList(incident),
      '',
      `## Related Issues`,
      ...(related.length > 0 ? related.map((id) => `- ${formatRelatedIssue(id)}`) : ['- None recorded']),
      '',
      '_Generated by Wavemill incident detector from confirmed, deduplicated incident state._',
    ].join('\n');
  }

  formatEvidenceComment(incident: IncidentRecord, revision: number): string {
    return [
      `## Evidence Update (Revision ${revision}, Occurrences ${incident.occurrenceCount})`,
      `Fingerprint: ${incident.fingerprint}`,
      `Window: ${incident.createdAt || '(unknown)'} to ${incident.lastObservedAt || '(unknown)'}`,
      '',
      ...formatEvidenceList(incident),
      '',
      '_Auto-generated from Wavemill incident state. Update metadata in the local incident store controls duplicate suppression._',
    ].join('\n');
  }

  formatCommentAsUpdate(incident: IncidentRecord, oldRevision: number, newRevision: number): string {
    return [
      `## Evidence Update (Revision ${newRevision}, previous ${oldRevision})`,
      `Occurrences: ${incident.occurrenceCount}`,
      '',
      ...formatEvidenceList(incident),
    ].join('\n');
  }
}

export function evidenceHash(incident: IncidentRecord): string {
  const payload = {
    occurrenceCount: incident.occurrenceCount,
    lastObservedAt: incident.lastObservedAt,
    evidence: incident.evidence.map((item) => ({
      type: item.type,
      source: item.source,
      timestamp: item.timestamp,
      lineNumber: item.lineNumber,
      key: item.key,
      redactedData: redactSensitiveContent(item.redactedData),
    })),
  };
  return createHash('sha256').update(JSON.stringify(payload)).digest('hex');
}

export function redactSensitiveContent(text: string): string {
  return text
    .replace(/\b(sk-[A-Za-z0-9_-]{12,}|pk_live_[A-Za-z0-9_-]{12,})\b/g, '[redacted-token]')
    .replace(/\b(OPENAI_API_KEY|ANTHROPIC_API_KEY|OPENROUTER_API_KEY|LINEAR_API_KEY|GITHUB_TOKEN|GH_TOKEN|WAVEMILL_SESSION|API_KEY|TOKEN|SECRET|PASSWORD)=("[^"]*"|'[^']*'|\S+)/gi, '$1=[redacted]')
    .replace(/\b(Authorization:\s*)?(Bearer|Basic)\s+[A-Za-z0-9._~+/=-]{12,}/gi, '$1$2 [redacted]')
    .replace(/\b(jwt|oauth[_-]?token|access[_-]?token|refresh[_-]?token)=\S+/gi, '$1=[redacted]')
    .replace(/\b(prompt|instructions|transcript)(\s*(?:=|:)\s*)(.+)$/gim, '$1$2[redacted]')
    .replace(/\b(write code that|create a function|system prompt|conversation transcript)\b.*$/gim, '[redacted-prompt-content]');
}

function formatEvidenceList(incident: IncidentRecord): string[] {
  const evidence = incident.evidence.slice(-MAX_EVIDENCE_ITEMS);
  if (evidence.length === 0) return ['- No evidence entries recorded.'];
  return evidence.map((item) => {
    const location = item.lineNumber ? `${item.source}:${item.lineNumber}` : item.source;
    const key = item.key ? ` key=${item.key}` : '';
    return `- ${item.timestamp} ${item.type} ${redactSensitiveContent(location)}${key}: ${redactSensitiveContent(item.redactedData)}`;
  });
}

function relatedIssueIds(incident: IncidentRecord, config: IncidentLinearConfig): string[] {
  const ids = new Set<string>();
  for (const value of [incident.metadata.linearRelatedIssueId, incident.metadata.relatedLinearId]) {
    if (typeof value === 'string' && value.trim()) ids.add(value.trim());
  }
  const policy = config.policies?.[incident.category];
  for (const value of policy?.correlateWith ?? []) {
    if (value.trim()) ids.add(value.trim());
  }
  return [...ids];
}

function formatRelatedIssue(id: string): string {
  if (/^[A-Z]+-\d+(?:_c)?$/.test(id)) {
    return `[${id}](https://linear.app/hokusai/issue/${id})`;
  }
  return redactSensitiveContent(id);
}

function sanitizeLine(value: string): string {
  return redactSensitiveContent(value).replace(/[\r\n]+/g, ' ').replace(/\s+/g, ' ').trim();
}
