export type AttributionSignal =
  | 'firstPartyRoute'
  | 'botAuthor'
  | 'coAuthoredBy'
  | 'branchPrefix'
  | 'label'
  | 'commitSignature';

export type AttributionConfidence = 'verified' | 'strong' | 'weak';

export type HarnessId =
  | 'github-copilot'
  | 'claude-code'
  | 'openai-codex'
  | 'cursor'
  | 'aider'
  | 'devin'
  | 'openhands'
  | 'sweep'
  | 'codegen'
  | 'swe-agent'
  | 'wavemill'
  | string; // allow extensibility for custom harnessess

export interface PullRequestInput {
  number: number;
  title?: string;
  authorLogin: string | null;
  authorType: string | null;
  headRef: string | null;
  labels: string[];
  mergedAt: string;
  commitMessages: string[];
  body?: string;
  headSha?: string;
}

export interface AttributionEvidence {
  signal: AttributionSignal;
  dimension: 'agentAuthored' | 'harness' | 'model';
  value: string; // raw matched value (login, trailer, prefix, …)
  rule: string; // e.g. 'branch-prefix:codex/', 'first-party:executed-route'
  confidence: AttributionConfidence;
}

export interface DimensionAttribution {
  value: string | 'unknown'; // agentAuthored uses 'agent' | 'unknown'
  confidence: AttributionConfidence | null; // null iff value === 'unknown'
  conflict: boolean; // same-tier disagreement collapsed to unknown
  evidence: AttributionEvidence[]; // all contributing evidence, kept even on unknown
}

export interface PrAttribution {
  number: number;
  signals: AttributionSignal[]; // which signals fired at all (coverage-by-signal)
  agentAuthored: DimensionAttribution;
  harness: DimensionAttribution;
  model: DimensionAttribution;
}

export interface SignalEvidence {
  pr: number;
  signal: AttributionSignal;
  value: string;
  rule: string;
}

export interface AttributedPullRequest {
  number: number;
  signals: AttributionSignal[];
  evidence: SignalEvidence[];
}

export interface AttributionSummary {
  repo: string;
  sampledMergedPrs: number;
  signalCounts: Record<AttributionSignal, number>;
  unionCount: number;
  unattributedCount: number;
  coverage: Record<AttributionSignal | 'union' | 'unattributed', number>;
  pullRequests: AttributedPullRequest[];
}

interface GitHubPullRequest {
  number: unknown;
  title?: unknown;
  user?: { login?: unknown; type?: unknown } | null;
  head?: { ref?: unknown; sha?: unknown } | null;
  labels?: Array<{ name?: unknown }> | null;
  merged_at?: unknown;
  body?: unknown;
}

interface GitHubCommit {
  commit?: { message?: unknown } | null;
}

export const DETECTOR_SIGNATURES = {
  botLogins: [
    'copilot',
    'copilot-swe-agent',
    'copilot-swe-agent[bot]',
    'github-copilot[bot]',
    'claude',
    'claude[bot]',
    'anthropic-code-agent[bot]',
    'cursor[bot]',
    'devin-ai-integration[bot]',
    'devin-ai[bot]',
    'openhands-agent[bot]',
    'sweep-ai[bot]',
    'codegen-sh[bot]',
    'codex[bot]',
    'openai-codex[bot]',
  ],
  coAuthorFragments: [
    'claude',
    'anthropic',
    'copilot',
    'codex',
    'openai',
    'cursor',
    'aider',
    'devin',
    'openhands',
    'sweep ai',
    'swe-agent',
    'codegen',
  ],
  branchPrefixes: [
    'codex/',
    'codex-',
    'copilot/',
    'copilot-',
    'cursor/',
    'cursor-',
    'claude/',
    'claude-',
    'aider/',
    'aider-',
    'devin/',
    'devin-',
    'openhands/',
    'openhands-',
    'swe-agent/',
    'swe-agent-',
    'ai-agent/',
    'agent/',
  ],
  labelNames: [
    'ai-generated',
    'ai generated',
    'ai-agent',
    'ai agent',
    'agent-authored',
    'agent authored',
    'copilot',
    'github copilot',
    'copilot-swe-agent',
    'codex',
    'openai codex',
    'claude',
    'claude code',
    'cursor',
    'aider',
    'devin',
    'openhands',
    'sweep ai',
    'codegen',
  ],
  commitSignatureFragments: [
    'generated with claude code',
    'generated by claude code',
    'generated with openai codex',
    'generated by openai codex',
    'generated by codex',
    'generated with codex',
    'generated with github copilot',
    'generated by github copilot',
    'copilot-swe-agent',
    'written by aider',
    'generated by aider',
    'devin ai',
    'openhands agent',
    'sweep ai',
    'codegen ai',
  ],
} as const;

export const SIGNAL_ORDER: AttributionSignal[] = [
  'firstPartyRoute',
  'botAuthor',
  'commitSignature',
  'coAuthoredBy',
  'branchPrefix',
  'label',
];

function normalized(value: string): string {
  return value.toLocaleLowerCase().trim();
}

export function pct(count: number, denominator: number): number {
  if (denominator === 0) return 0;
  return Number(((count / denominator) * 100).toFixed(1));
}

function addEvidence(
  evidenceBySignal: Map<AttributionSignal, SignalEvidence>,
  signal: AttributionSignal,
  pr: number,
  value: string,
  rule: string,
): void {
  if (!evidenceBySignal.has(signal)) {
    evidenceBySignal.set(signal, { pr, signal, value, rule });
  }
}

export function extractCoAuthorTrailers(message: string): string[] {
  const trailers: string[] = [];
  for (const line of message.split(/\r?\n/)) {
    const match = line.match(/^Co-authored-by:\s*(.+)$/i);
    if (match) {
      trailers.push(match[1].trim());
    }
  }
  return trailers;
}

export function validateRepoSlug(repo: string): string {
  const trimmed = repo.trim();
  if (!/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(trimmed)) {
    throw new Error(`Invalid repository slug: ${repo}`);
  }
  return trimmed;
}

export function analyzePullRequest(pr: PullRequestInput): AttributedPullRequest {
  const evidenceBySignal = new Map<AttributionSignal, SignalEvidence>();
  const authorLogin = pr.authorLogin ? normalized(pr.authorLogin) : '';
  const authorType = pr.authorType ? normalized(pr.authorType) : '';

  if (authorLogin && DETECTOR_SIGNATURES.botLogins.includes(authorLogin as never)) {
    addEvidence(
      evidenceBySignal,
      'botAuthor',
      pr.number,
      pr.authorLogin ?? '',
      'known-agent-bot-login',
    );
  } else if (authorType === 'bot') {
    const stripped = authorLogin.replace(/\[bot\]$/, '');
    if (DETECTOR_SIGNATURES.botLogins.includes(stripped as never)) {
      addEvidence(
        evidenceBySignal,
        'botAuthor',
        pr.number,
        pr.authorLogin ?? '',
        'known-agent-bot-type-login',
      );
    }
  }

  for (const message of pr.commitMessages) {
    for (const trailer of extractCoAuthorTrailers(message)) {
      const trailerText = normalized(trailer);
      const matched = DETECTOR_SIGNATURES.coAuthorFragments.find((fragment) =>
        trailerText.includes(fragment),
      );
      if (matched) {
        addEvidence(
          evidenceBySignal,
          'coAuthoredBy',
          pr.number,
          trailer,
          `co-author-fragment:${matched}`,
        );
      }
    }
  }

  if (pr.headRef) {
    const headRef = normalized(pr.headRef);
    const matched = DETECTOR_SIGNATURES.branchPrefixes.find((prefix) =>
      headRef.startsWith(prefix),
    );
    if (matched) {
      addEvidence(evidenceBySignal, 'branchPrefix', pr.number, pr.headRef, `branch-prefix:${matched}`);
    }
  }

  for (const label of pr.labels) {
    const labelName = normalized(label);
    const matched = DETECTOR_SIGNATURES.labelNames.find((candidate) => labelName === candidate);
    if (matched) {
      addEvidence(evidenceBySignal, 'label', pr.number, label, `label:${matched}`);
    }
  }

  for (const message of pr.commitMessages) {
    const messageText = normalized(message);
    const matched = DETECTOR_SIGNATURES.commitSignatureFragments.find((fragment) =>
      messageText.includes(fragment),
    );
    if (matched) {
      addEvidence(
        evidenceBySignal,
        'commitSignature',
        pr.number,
        matched,
        `commit-signature:${matched}`,
      );
    }
  }

  const evidence = [...evidenceBySignal.values()];
  return {
    number: pr.number,
    signals: evidence.map((item) => item.signal),
    evidence,
  };
}

export function summarizeAttribution(repo: string, prs: PullRequestInput[]): AttributionSummary {
  const pullRequests = prs.map(analyzePullRequest);
  const signalCounts = Object.fromEntries(
    SIGNAL_ORDER.map((signal) => [signal, 0]),
  ) as Record<AttributionSignal, number>;

  for (const pr of pullRequests) {
    for (const signal of pr.signals) {
      signalCounts[signal] += 1;
    }
  }

  const unionCount = pullRequests.filter((pr) => pr.signals.length > 0).length;
  const unattributedCount = prs.length - unionCount;
  const coverage = Object.fromEntries([
    ...SIGNAL_ORDER.map((signal) => [signal, pct(signalCounts[signal], prs.length)]),
    ['union', pct(unionCount, prs.length)],
    ['unattributed', pct(unattributedCount, prs.length)],
  ]) as Record<AttributionSignal | 'union' | 'unattributed', number>;

  return {
    repo,
    sampledMergedPrs: prs.length,
    signalCounts,
    unionCount,
    unattributedCount,
    coverage,
    pullRequests,
  };
}

export function parseGitHubPullRequest(raw: unknown, commitMessages: string[]): PullRequestInput {
  if (!raw || typeof raw !== 'object') {
    throw new Error('Malformed pull request response: expected object');
  }
  const pr = raw as GitHubPullRequest;
  if (typeof pr.number !== 'number') {
    throw new Error('Malformed pull request response: missing numeric number');
  }
  if (typeof pr.merged_at !== 'string' || pr.merged_at.length === 0) {
    throw new Error(`Malformed pull request response for #${pr.number}: missing merged_at`);
  }
  if (!Array.isArray(pr.labels)) {
    throw new Error(`Malformed pull request response for #${pr.number}: missing labels array`);
  }

  return {
    number: pr.number,
    title: typeof pr.title === 'string' ? pr.title : undefined,
    authorLogin: typeof pr.user?.login === 'string' ? pr.user.login : null,
    authorType: typeof pr.user?.type === 'string' ? pr.user.type : null,
    headRef: typeof pr.head?.ref === 'string' ? pr.head.ref : null,
    headSha: typeof pr.head?.sha === 'string' ? pr.head.sha : undefined,
    labels: pr.labels.map((label) => {
      if (typeof label?.name !== 'string') {
        throw new Error(`Malformed pull request response for #${pr.number}: label without name`);
      }
      return label.name;
    }),
    mergedAt: pr.merged_at,
    body: typeof pr.body === 'string' ? pr.body : undefined,
    commitMessages,
  };
}

export function parseGitHubCommitMessages(raw: unknown, prNumber: number): string[] {
  if (!Array.isArray(raw)) {
    throw new Error(`Malformed commits response for PR #${prNumber}: expected array`);
  }

  return raw.map((commit, index) => {
    const message = (commit as GitHubCommit)?.commit?.message;
    if (typeof message !== 'string') {
      throw new Error(
        `Malformed commits response for PR #${prNumber}: commit ${index + 1} missing message`,
      );
    }
    return message;
  });
}

export function parseReposFileContent(content: string): string[] {
  const trimmed = content.trim();
  if (!trimmed) return [];

  if (trimmed.startsWith('[')) {
    const parsed = JSON.parse(trimmed);
    if (!Array.isArray(parsed) || parsed.some((item) => typeof item !== 'string')) {
      throw new Error('Repository JSON file must be an array of slugs');
    }
    return parsed.map(validateRepoSlug);
  }

  return trimmed
    .split(/\r?\n/)
    .map((line) => line.replace(/#.*$/, '').trim())
    .filter(Boolean)
    .map(validateRepoSlug);
}

// Three-dimension engine: harness/model mapping

interface SignatureMapping {
  agentAuthored: 'agent'; // always agent when a signal fires
  harness?: HarnessId;
  model?: string;
}

type BotLoginMapping = Record<string, SignatureMapping>;
type CoAuthorMapping = Record<string, SignatureMapping>;
type BranchPrefixMapping = Record<string, SignatureMapping>;
type LabelMapping = Record<string, SignatureMapping>;
type CommitSignatureMapping = Record<string, SignatureMapping>;

const BOT_LOGIN_MAPPING: BotLoginMapping = {
  'copilot': { agentAuthored: 'agent', harness: 'github-copilot' },
  'copilot-swe-agent': { agentAuthored: 'agent', harness: 'github-copilot' },
  'copilot-swe-agent[bot]': { agentAuthored: 'agent', harness: 'github-copilot' },
  'github-copilot[bot]': { agentAuthored: 'agent', harness: 'github-copilot' },
  'claude': { agentAuthored: 'agent', harness: 'claude-code' },
  'claude[bot]': { agentAuthored: 'agent', harness: 'claude-code' },
  'anthropic-code-agent[bot]': { agentAuthored: 'agent', harness: 'claude-code' },
  'cursor[bot]': { agentAuthored: 'agent', harness: 'cursor' },
  'devin-ai-integration[bot]': { agentAuthored: 'agent', harness: 'devin' },
  'devin-ai[bot]': { agentAuthored: 'agent', harness: 'devin' },
  'openhands-agent[bot]': { agentAuthored: 'agent', harness: 'openhands' },
  'sweep-ai[bot]': { agentAuthored: 'agent', harness: 'sweep' },
  'codegen-sh[bot]': { agentAuthored: 'agent', harness: 'codegen' },
  'codex[bot]': { agentAuthored: 'agent', harness: 'openai-codex' },
  'openai-codex[bot]': { agentAuthored: 'agent', harness: 'openai-codex' },
};

const COMMIT_SIGNATURE_MAPPING: CommitSignatureMapping = {
  'generated with claude code': { agentAuthored: 'agent', harness: 'claude-code' },
  'generated by claude code': { agentAuthored: 'agent', harness: 'claude-code' },
  'generated with openai codex': { agentAuthored: 'agent', harness: 'openai-codex' },
  'generated by openai codex': { agentAuthored: 'agent', harness: 'openai-codex' },
  'generated by codex': { agentAuthored: 'agent', harness: 'openai-codex' },
  'generated with codex': { agentAuthored: 'agent', harness: 'openai-codex' },
  'generated with github copilot': { agentAuthored: 'agent', harness: 'github-copilot' },
  'generated by github copilot': { agentAuthored: 'agent', harness: 'github-copilot' },
  'copilot-swe-agent': { agentAuthored: 'agent', harness: 'github-copilot' },
  'written by aider': { agentAuthored: 'agent', harness: 'aider' },
  'generated by aider': { agentAuthored: 'agent', harness: 'aider' },
  'devin ai': { agentAuthored: 'agent', harness: 'devin' },
  'openhands agent': { agentAuthored: 'agent', harness: 'openhands' },
  'sweep ai': { agentAuthored: 'agent', harness: 'sweep' },
  'codegen ai': { agentAuthored: 'agent', harness: 'codegen' },
};

// Model-bearing trailer registry: exact model names extracted from trailer text
const MODEL_BEARING_TRAILERS: Record<string, string> = {
  'claude fable 5': 'claude-fable-5-1',
  'claude opus 5': 'claude-opus-5',
  'claude sonnet 5': 'claude-sonnet-5',
  'claude opus 4.5': 'claude-opus-4-5',
  'claude sonnet 4': 'claude-sonnet-4',
  'claude opus 4': 'claude-opus-4',
  'claude 3.5 sonnet': 'claude-3-5-sonnet-20241022',
  'claude 3.5 haiku': 'claude-3-5-haiku-20241022',
  'claude 3 opus': 'claude-3-opus-20240229',
  'claude 3 sonnet': 'claude-3-sonnet-20240229',
};

const BRANCH_PREFIX_MAPPING: BranchPrefixMapping = {
  'codex/': { agentAuthored: 'agent', harness: 'openai-codex' },
  'codex-': { agentAuthored: 'agent', harness: 'openai-codex' },
  'copilot/': { agentAuthored: 'agent', harness: 'github-copilot' },
  'copilot-': { agentAuthored: 'agent', harness: 'github-copilot' },
  'cursor/': { agentAuthored: 'agent', harness: 'cursor' },
  'cursor-': { agentAuthored: 'agent', harness: 'cursor' },
  'claude/': { agentAuthored: 'agent', harness: 'claude-code' },
  'claude-': { agentAuthored: 'agent', harness: 'claude-code' },
  'aider/': { agentAuthored: 'agent', harness: 'aider' },
  'aider-': { agentAuthored: 'agent', harness: 'aider' },
  'devin/': { agentAuthored: 'agent', harness: 'devin' },
  'devin-': { agentAuthored: 'agent', harness: 'devin' },
  'openhands/': { agentAuthored: 'agent', harness: 'openhands' },
  'openhands-': { agentAuthored: 'agent', harness: 'openhands' },
  'swe-agent/': { agentAuthored: 'agent', harness: 'swe-agent' },
  'swe-agent-': { agentAuthored: 'agent', harness: 'swe-agent' },
  'ai-agent/': { agentAuthored: 'agent' },
  'agent/': { agentAuthored: 'agent' },
};

const LABEL_MAPPING: LabelMapping = {
  'ai-generated': { agentAuthored: 'agent' },
  'ai generated': { agentAuthored: 'agent' },
  'ai-agent': { agentAuthored: 'agent' },
  'ai agent': { agentAuthored: 'agent' },
  'agent-authored': { agentAuthored: 'agent' },
  'agent authored': { agentAuthored: 'agent' },
  'copilot': { agentAuthored: 'agent', harness: 'github-copilot' },
  'github copilot': { agentAuthored: 'agent', harness: 'github-copilot' },
  'copilot-swe-agent': { agentAuthored: 'agent', harness: 'github-copilot' },
  'codex': { agentAuthored: 'agent', harness: 'openai-codex' },
  'openai codex': { agentAuthored: 'agent', harness: 'openai-codex' },
  'claude': { agentAuthored: 'agent', harness: 'claude-code' },
  'claude code': { agentAuthored: 'agent', harness: 'claude-code' },
  'cursor': { agentAuthored: 'agent', harness: 'cursor' },
  'aider': { agentAuthored: 'agent', harness: 'aider' },
  'devin': { agentAuthored: 'agent', harness: 'devin' },
  'openhands': { agentAuthored: 'agent', harness: 'openhands' },
  'sweep ai': { agentAuthored: 'agent', harness: 'sweep' },
  'codegen': { agentAuthored: 'agent', harness: 'codegen' },
};

interface HeuristicSignalWithConfidence {
  signal: AttributionSignal;
  dimension: 'agentAuthored' | 'harness' | 'model';
  value: string;
  mapping: SignatureMapping;
  confidence: AttributionConfidence;
  order: number; // for precedence comparison within tier
}

function collectDimensionEvidence(
  pr: PullRequestInput,
  disabledSignals: Set<AttributionSignal> = new Set(),
): HeuristicSignalWithConfidence[] {
  const evidence: HeuristicSignalWithConfidence[] = [];
  const authorLogin = pr.authorLogin ? normalized(pr.authorLogin) : '';
  const authorType = pr.authorType ? normalized(pr.authorType) : '';

  // botAuthor detection (precedence: 4)
  if (!disabledSignals.has('botAuthor')) {
    let match: SignatureMapping | null = null;
    let rawValue = '';

    if (authorLogin && BOT_LOGIN_MAPPING[authorLogin]) {
      match = BOT_LOGIN_MAPPING[authorLogin];
      rawValue = pr.authorLogin ?? '';
    } else if (authorType === 'bot') {
      const stripped = authorLogin.replace(/\[bot\]$/, '');
      if (BOT_LOGIN_MAPPING[stripped]) {
        match = BOT_LOGIN_MAPPING[stripped];
        rawValue = pr.authorLogin ?? '';
      }
    }

    if (match) {
      if (match.agentAuthored) {
        evidence.push({
          signal: 'botAuthor',
          dimension: 'agentAuthored',
          value: rawValue,
          mapping: match,
          confidence: 'strong',
          order: 4,
        });
      }
      if (match.harness) {
        evidence.push({
          signal: 'botAuthor',
          dimension: 'harness',
          value: rawValue,
          mapping: match,
          confidence: 'strong',
          order: 4,
        });
      }
    }
  }

  // commitSignature detection (precedence: 5)
  if (!disabledSignals.has('commitSignature')) {
    for (const message of pr.commitMessages) {
      const messageText = normalized(message);
      for (const [fragment, mapping] of Object.entries(COMMIT_SIGNATURE_MAPPING)) {
        if (messageText.includes(fragment)) {
          if (mapping.agentAuthored) {
            evidence.push({
              signal: 'commitSignature',
              dimension: 'agentAuthored',
              value: fragment,
              mapping,
              confidence: 'strong',
              order: 5,
            });
          }
          if (mapping.harness) {
            evidence.push({
              signal: 'commitSignature',
              dimension: 'harness',
              value: fragment,
              mapping,
              confidence: 'strong',
              order: 5,
            });
          }
          break; // one match per message
        }
      }
    }
  }

  // coAuthoredBy detection (precedence: 6)
  if (!disabledSignals.has('coAuthoredBy')) {
    let foundModelTrailer = false; // Only use first model-bearing trailer globally
    for (const message of pr.commitMessages) {
      for (const trailer of extractCoAuthorTrailers(message)) {
        const trailerNorm = normalized(trailer);
        let foundMatch = false;

        // Check for model-bearing trailers first (but only use the first one overall)
        if (!foundModelTrailer) {
          for (const [trailerPattern, modelId] of Object.entries(MODEL_BEARING_TRAILERS)) {
            if (trailerNorm.includes(trailerPattern)) {
              evidence.push({
                signal: 'coAuthoredBy',
                dimension: 'agentAuthored',
                value: trailer,
                mapping: { agentAuthored: 'agent' },
                confidence: 'strong',
                order: 6,
              });
              evidence.push({
                signal: 'coAuthoredBy',
                dimension: 'harness',
                value: trailer,
                mapping: { agentAuthored: 'agent', harness: 'claude-code' }, // assume claude-code for model trailer
                confidence: 'strong',
                order: 6,
              });
              evidence.push({
                signal: 'coAuthoredBy',
                dimension: 'model',
                value: trailer,
                mapping: { agentAuthored: 'agent', model: modelId },
                confidence: 'strong',
                order: 6,
              });
              foundMatch = true;
              foundModelTrailer = true; // Don't use any more model trailers
              break;
            }
          }
        }

        // If no model trailer match, check for generic agent fragments (harness only)
        if (!foundMatch) {
          const matched = DETECTOR_SIGNATURES.coAuthorFragments.find((fragment) =>
            trailerNorm.includes(fragment),
          );
          if (matched) {
            const harnessMap: Record<string, HarnessId> = {
              'claude': 'claude-code',
              'anthropic': 'claude-code',
              'copilot': 'github-copilot',
              'codex': 'openai-codex',
              'openai': 'openai-codex',
              'cursor': 'cursor',
              'aider': 'aider',
              'devin': 'devin',
              'openhands': 'openhands',
              'sweep ai': 'sweep',
              'swe-agent': 'swe-agent',
              'codegen': 'codegen',
            };

            evidence.push({
              signal: 'coAuthoredBy',
              dimension: 'agentAuthored',
              value: trailer,
              mapping: { agentAuthored: 'agent' },
              confidence: 'strong',
              order: 6,
            });

            if (harnessMap[matched]) {
              evidence.push({
                signal: 'coAuthoredBy',
                dimension: 'harness',
                value: trailer,
                mapping: { agentAuthored: 'agent', harness: harnessMap[matched] },
                confidence: 'strong',
                order: 6,
              });
            }
          }
        }
      }
    }
  }

  // branchPrefix detection (precedence: 7)
  if (!disabledSignals.has('branchPrefix') && pr.headRef) {
    const headRef = normalized(pr.headRef);
    for (const [prefix, mapping] of Object.entries(BRANCH_PREFIX_MAPPING)) {
      if (headRef.startsWith(prefix)) {
        if (mapping.agentAuthored) {
          evidence.push({
            signal: 'branchPrefix',
            dimension: 'agentAuthored',
            value: pr.headRef,
            mapping,
            confidence: 'weak',
            order: 7,
          });
        }
        if (mapping.harness) {
          evidence.push({
            signal: 'branchPrefix',
            dimension: 'harness',
            value: pr.headRef,
            mapping,
            confidence: 'weak',
            order: 7,
          });
        }
        break; // one match per branch
      }
    }
  }

  // label detection (precedence: 8)
  if (!disabledSignals.has('label')) {
    for (const label of pr.labels) {
      const labelName = normalized(label);
      const mapping = LABEL_MAPPING[labelName];
      if (mapping) {
        if (mapping.agentAuthored) {
          evidence.push({
            signal: 'label',
            dimension: 'agentAuthored',
            value: label,
            mapping,
            confidence: 'weak',
            order: 8,
          });
        }
        if (mapping.harness) {
          evidence.push({
            signal: 'label',
            dimension: 'harness',
            value: label,
            mapping,
            confidence: 'weak',
            order: 8,
          });
        }
      }
    }
  }

  return evidence;
}

function resolveDimensionFromEvidence(
  evidence: HeuristicSignalWithConfidence[],
  dimension: 'agentAuthored' | 'harness' | 'model',
  disabledSignals: Set<AttributionSignal>,
): DimensionAttribution {
  // Filter to this dimension
  const dimEvidence = evidence.filter((e) => e.dimension === dimension && !disabledSignals.has(e.signal));

  if (dimEvidence.length === 0) {
    return {
      value: 'unknown',
      confidence: null,
      conflict: false,
      evidence: [],
    };
  }

  // Group by confidence tier
  const byConfidence: Record<AttributionConfidence, HeuristicSignalWithConfidence[]> = {
    verified: [],
    strong: [],
    weak: [],
  };

  for (const e of dimEvidence) {
    byConfidence[e.confidence].push(e);
  }

  // Highest tier wins (verified > strong > weak)
  for (const tier of ['verified', 'strong', 'weak'] as const) {
    if (byConfidence[tier].length === 0) continue;

    const tierEvidence = byConfidence[tier];

    // Within a tier, sort by signal precedence (lower order number = higher precedence)
    tierEvidence.sort((a, b) => a.order - b.order);

    const topOrder = tierEvidence[0].order;
    const topCandidates = tierEvidence.filter((e) => e.order === topOrder);

    // Extract values to check for conflicts
    const extractValue = (e: HeuristicSignalWithConfidence): string => {
      if (dimension === 'agentAuthored') {
        return e.mapping.agentAuthored ?? 'unknown';
      } else if (dimension === 'harness') {
        return e.mapping.harness ?? 'unknown';
      } else if (dimension === 'model') {
        return e.mapping.model ?? 'unknown';
      }
      return 'unknown';
    };

    // agentAuthored never conflicts (all "agent" values)
    if (dimension === 'agentAuthored') {
      return {
        value: 'agent',
        confidence: tier,
        conflict: false,
        // Include all evidence from the winning tier (all agree on "agent")
        evidence: tierEvidence.map((e) => ({
          signal: e.signal,
          dimension,
          value: e.value,
          rule: `${e.signal}:${e.value}`,
          confidence: tier,
        })),
      };
    }

    // Check for distinct values at top precedence
    const uniqueValues = new Set<string>();
    const byValue = new Map<string, HeuristicSignalWithConfidence[]>();

    for (const e of topCandidates) {
      const value = extractValue(e);
      uniqueValues.add(value);
      if (!byValue.has(value)) {
        byValue.set(value, []);
      }
      byValue.get(value)!.push(e);
    }

    if (uniqueValues.size === 1) {
      // No conflict: only include winning tier evidence
      const value = [...uniqueValues][0];
      return {
        value: value === 'unknown' ? 'unknown' : value,
        confidence: value === 'unknown' ? null : tier,
        conflict: false,
        evidence: topCandidates.map((e) => ({
          signal: e.signal,
          dimension,
          value: e.value,
          rule: `${e.signal}:${e.value}`,
          confidence: tier,
        })),
      };
    }

    // Conflict: multiple distinct values at same tier
    // Include ALL evidence from this tier (not just top candidates) for full transparency
    return {
      value: 'unknown',
      confidence: null,
      conflict: true,
      evidence: tierEvidence.map((e) => ({
        signal: e.signal,
        dimension,
        value: e.value,
        rule: `${e.signal}:${e.value}`,
        confidence: tier,
      })),
    };
  }

  return {
    value: 'unknown',
    confidence: null,
    conflict: false,
    evidence: [],
  };
}

interface ExecutedRouteStatus {
  planner?: ExecutedRoleRoute;
  coder?: ExecutedRoleRoute;
  reviewer?: ExecutedRoleRoute;
}

interface ExecutedRoleRoute {
  model: string;
  adapter: string;
  status: 'executed' | 'inherited' | 'not_run' | 'unknown';
  evidence?: string;
  headSha?: string;
}

interface ExecutedRouteExtraction {
  valid: boolean;
  error?: string;
  status?: ExecutedRouteStatus;
  raw?: string;
}

function lentientlyExtractWavemillMeta(body: string | undefined): string | null {
  if (!body) return null;

  // Last block wins (matches extractMetadataBlock semantics)
  let block: string | null = null;
  const regex = /<!-- wavemill-meta\n([\s\S]*?)\n-->/g;

  for (const match of body.matchAll(regex)) {
    block = match[1] ?? '';
  }

  return block;
}

function validateExecutedRoute(route: unknown, headSha: string | undefined): ExecutedRouteExtraction {
  if (typeof route !== 'object' || route === null) {
    return { valid: false, error: 'not-an-object' };
  }

  const status: ExecutedRouteStatus = {};
  const roles: Array<'planner' | 'coder' | 'reviewer'> = ['planner', 'coder', 'reviewer'];

  for (const role of roles) {
    const entry = (route as Record<string, unknown>)[role];
    if (!entry) continue;

    if (typeof entry !== 'object' || entry === null) {
      return { valid: false, error: `role-${role}-not-object` };
    }

    const e = entry as Record<string, unknown>;
    const model = e.model;
    const adapter = e.adapter;
    const stat = e.status;

    if (typeof model !== 'string' || !model) {
      return { valid: false, error: `role-${role}-missing-model` };
    }
    if (typeof adapter !== 'string' || !adapter) {
      return { valid: false, error: `role-${role}-missing-adapter` };
    }
    if (!['executed', 'inherited', 'not_run', 'unknown'].includes(stat as string)) {
      return { valid: false, error: `role-${role}-invalid-status` };
    }

    // If status is 'executed', check head SHA freshness
    if (stat === 'executed') {
      const roleHeadSha = e.headSha;
      if (roleHeadSha && typeof roleHeadSha === 'string' && headSha && roleHeadSha !== headSha) {
        // Stale: head SHA doesn't match PR head
        status[role as 'planner' | 'coder' | 'reviewer'] = {
          model,
          adapter,
          status: 'unknown', // Treat stale as unknown
          evidence: 'stale-head-sha',
          headSha: roleHeadSha,
        };
        continue;
      }
    }

    status[role as 'planner' | 'coder' | 'reviewer'] = {
      model,
      adapter,
      status: stat as 'executed' | 'inherited' | 'not_run' | 'unknown',
      headSha: typeof e.headSha === 'string' ? e.headSha : undefined,
    };
  }

  return { valid: true, status, raw: JSON.stringify(route) };
}

function extractFirstPartyRoute(
  pr: PullRequestInput,
  disabledSignals: Set<AttributionSignal>,
): HeuristicSignalWithConfidence[] {
  if (disabledSignals.has('firstPartyRoute') || !pr.body || !pr.headSha) {
    return [];
  }

  const evidence: HeuristicSignalWithConfidence[] = [];
  const block = lentientlyExtractWavemillMeta(pr.body);
  if (!block) return [];

  let routeSchema: string | null = null;
  let executedRouteJson: string | null = null;

  for (const line of block.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed) continue;

    const match = trimmed.match(/^route_schema:\s*(.+)$/);
    if (match) {
      routeSchema = match[1].trim();
      continue;
    }

    const match2 = trimmed.match(/^executed_route:\s*(.+)$/);
    if (match2) {
      executedRouteJson = match2[1].trim();
      continue;
    }
  }

  if (!routeSchema || routeSchema !== '1') {
    return []; // Wrong or missing schema version
  }

  if (!executedRouteJson) {
    return []; // Missing executed_route
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(executedRouteJson);
  } catch {
    // Malformed JSON
    return [];
  }

  const extraction = validateExecutedRoute(parsed, pr.headSha);
  if (!extraction.valid || !extraction.status) {
    return [];
  }

  // Only use executed coder role with valid head SHA
  const coderRoute = extraction.status.coder;
  if (coderRoute && coderRoute.status === 'executed') {
    evidence.push({
      signal: 'firstPartyRoute',
      dimension: 'agentAuthored',
      value: 'agent',
      mapping: { agentAuthored: 'agent' },
      confidence: 'verified',
      order: 1, // Highest precedence
    });

    evidence.push({
      signal: 'firstPartyRoute',
      dimension: 'harness',
      value: coderRoute.adapter,
      mapping: { agentAuthored: 'agent', harness: coderRoute.adapter as HarnessId },
      confidence: 'verified',
      order: 1,
    });

    evidence.push({
      signal: 'firstPartyRoute',
      dimension: 'model',
      value: coderRoute.model,
      mapping: { agentAuthored: 'agent', model: coderRoute.model },
      confidence: 'verified',
      order: 1,
    });
  }

  return evidence;
}

export function attributePullRequest(
  pr: PullRequestInput,
  disabledSignals: Set<AttributionSignal> = new Set(),
): PrAttribution {
  // Phase 3: Extract first-party route (highest precedence)
  const firstPartyEvidence = extractFirstPartyRoute(pr, disabledSignals);

  // Collect all heuristic evidence (Phase 2)
  const heuristicEvidence = collectDimensionEvidence(pr, disabledSignals);

  // Combine evidence: first-party takes absolute precedence
  const allEvidence = [...firstPartyEvidence, ...heuristicEvidence];

  // Resolve each dimension independently
  const agentAuthored = resolveDimensionFromEvidence(allEvidence, 'agentAuthored', disabledSignals);
  const harness = resolveDimensionFromEvidence(allEvidence, 'harness', disabledSignals);
  const model = resolveDimensionFromEvidence(allEvidence, 'model', disabledSignals);

  // Extract unique signals that fired (including firstPartyRoute)
  const signals = new Set<AttributionSignal>(
    allEvidence.map((e) => e.signal).filter((s) => !disabledSignals.has(s)),
  );

  return {
    number: pr.number,
    signals: Array.from(signals),
    agentAuthored,
    harness,
    model,
  };
}
